const id = "faq.md";
						const collection = "sections";
						const slug = "faq";
						const body = "";
						const data = {enable:true,subtitle:"COMMON INQUIRIES",title:"Frequently Asked Questions",description:"Donec rutrum congue leo eget malesuada. Sed porttitor lectus nibh. Cras ultricies ligula sed magna dictum porta. Vestibulum ac diam sit amet quam vehicula elementum.",faqs:[{title:"How does the free trial work?",body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi quaerat veritatis necessitatibus nemo ullam dolores aut veniam officiis asperiores, unde quo magni repudiandae impedit iusto voluptatum eos, aliquam, consectetur aliquid."},{title:"Do I need a creditcard to Sign up?",body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi quaerat veritatis necessitatibus nemo ullam dolores aut veniam officiis asperiores, unde quo magni repudiandae impedit iusto voluptatum eos, aliquam, consectetur aliquid."},{title:"How does the free trial work?",body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi quaerat veritatis necessitatibus nemo ullam dolores aut veniam officiis asperiores, unde quo magni repudiandae impedit iusto voluptatum eos, aliquam, consectetur aliquid."},{title:"How does the free trial work?",body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi quaerat veritatis necessitatibus nemo ullam dolores aut veniam officiis asperiores, unde quo magni repudiandae impedit iusto voluptatum eos, aliquam, consectetur aliquid."},{title:"Do I need a creditcard to Sign up?",body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi quaerat veritatis necessitatibus nemo ullam dolores aut veniam officiis asperiores, unde quo magni repudiandae impedit iusto voluptatum eos, aliquam, consectetur aliquid."},{title:"Can I change my plan at any time?",body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi quaerat veritatis necessitatibus nemo ullam dolores aut veniam officiis asperiores, unde quo magni repudiandae impedit iusto voluptatum eos, aliquam, consectetur aliquid."}]};
						const _internal = {
							type: 'content',
							filePath: "/Users/zaidarivai/Desktop/website/omniheral_light/src/content/sections/faq.md",
							rawData: "\nenable: true\nsubtitle: \"COMMON INQUIRIES\"\ntitle: \"Frequently Asked Questions\"\ndescription: Donec rutrum congue leo eget malesuada. Sed porttitor lectus nibh. Cras ultricies ligula sed magna dictum porta. Vestibulum ac diam sit amet quam vehicula elementum.\n\n#Faqs\nfaqs:\n  - title: How does the free trial work?\n    body: Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi quaerat veritatis necessitatibus nemo ullam dolores aut veniam officiis asperiores, unde quo magni repudiandae impedit iusto voluptatum eos, aliquam, consectetur aliquid.\n  - title: Do I need a creditcard to Sign up?\n    body: Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi quaerat veritatis necessitatibus nemo ullam dolores aut veniam officiis asperiores, unde quo magni repudiandae impedit iusto voluptatum eos, aliquam, consectetur aliquid.\n  - title: How does the free trial work?\n    body: Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi quaerat veritatis necessitatibus nemo ullam dolores aut veniam officiis asperiores, unde quo magni repudiandae impedit iusto voluptatum eos, aliquam, consectetur aliquid.\n  - title: How does the free trial work?\n    body: Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi quaerat veritatis necessitatibus nemo ullam dolores aut veniam officiis asperiores, unde quo magni repudiandae impedit iusto voluptatum eos, aliquam, consectetur aliquid.\n  - title: Do I need a creditcard to Sign up?\n    body: Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi quaerat veritatis necessitatibus nemo ullam dolores aut veniam officiis asperiores, unde quo magni repudiandae impedit iusto voluptatum eos, aliquam, consectetur aliquid.\n  - title:  Can I change my plan at any time?\n    body: Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi quaerat veritatis necessitatibus nemo ullam dolores aut veniam officiis asperiores, unde quo magni repudiandae impedit iusto voluptatum eos, aliquam, consectetur aliquid.",
						};

export { _internal, body, collection, data, id, slug };
