const id = "pricing.md";
						const collection = "pages";
						const slug = "pricing";
						const body = "";
						const data = {title:"Choose the Plan That’s Right for You",meta_title:"",description:"this is meta description",draft:false,pricing:{subtitle:"CHOOSE PLAN FOR YOU",title:"Try Spydea for free Now",description:"Lorem ipsum dolor sit amet, consectetur mag na dictum porta. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. elementum id enim. Nulla quis lorem ut libero malesuada feugiat. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Quisque velit nisi, pretium ut",button:{enable:true,label:"Sign up For Free",link:"/register"},plans:[{title:"Standard license",icon:"/images/icons/award.png",subtitle:"Traffic Corporate Sites",price:"200 \u003Cspan>/month\u003C/span>",type:"Standard",content:["\u003Cstrong>Pellentesque\u003C/strong> dapibus quam","\u003Cstrong>Morbi convallis\u003C/strong> a urna quis lacinia","\u003Cstrong>Aliquam\u003C/strong> vehicula laoreet ligula","\u003Cstrong>Sed dapibus\u003C/strong> vitae mauris id fringilla"]},{title:"Enterprise License",icon:"/images/icons/price-tag.png",subtitle:"Traffic Corporate Sites",price:"500 \u003Cspan>/month\u003C/span>",type:"Enterprise",tag:"popular",content:["\u003Cstrong>Pellentesque\u003C/strong> dapibus quam","\u003Cstrong>Morbi convallis\u003C/strong> a urna quis lacinia","\u003Cstrong>Aliquam\u003C/strong> vehicula laoreet ligula","\u003Cstrong>Sed dapibus\u003C/strong> vitae mauris id fringilla"]}]}};
						const _internal = {
							type: 'content',
							filePath: "/Users/zaidarivai/Desktop/website/omniheral_light/src/content/pages/pricing.md",
							rawData: "\ntitle: \"Choose the Plan That’s Right for You\"\nmeta_title: \"\"\ndescription: \"this is meta description\"\ndraft: false\n\npricing:\n  subtitle: CHOOSE PLAN FOR YOU\n  title: Try Spydea for free Now\n  description: Lorem ipsum dolor sit amet, consectetur mag na dictum porta. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. elementum id enim. Nulla quis lorem ut libero malesuada feugiat. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Quisque velit nisi, pretium ut\n  button:\n    enable: true\n    label: Sign up For Free\n    link: \"/register\"\n  plans:\n    - title: Standard license\n      icon: \"/images/icons/award.png\"\n      subtitle: Traffic Corporate Sites\n      price: 200 <span>/month</span>\n      type: Standard\n      content:\n        - <strong>Pellentesque</strong> dapibus quam\n        - <strong>Morbi convallis</strong> a urna quis lacinia\n        - <strong>Aliquam</strong> vehicula laoreet ligula\n        - <strong>Sed dapibus</strong> vitae mauris id fringilla\n    - title: Enterprise License\n      icon: \"/images/icons/price-tag.png\"\n      subtitle: Traffic Corporate Sites\n      price: 500 <span>/month</span>\n      type: Enterprise\n      tag: popular\n      content:\n        - <strong>Pellentesque</strong> dapibus quam\n        - <strong>Morbi convallis</strong> a urna quis lacinia\n        - <strong>Aliquam</strong> vehicula laoreet ligula\n        - <strong>Sed dapibus</strong> vitae mauris id fringilla\n  \n",
						};

export { _internal, body, collection, data, id, slug };
