const id = "spotify.md";
						const collection = "integrations";
						const slug = "spotify";
						const body = "\n#### How to connect your store with figma\n\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Nulla quis lorem ut libero malesuada feugiat. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vivamus suscipit tortor eget felis porttitor volutpat. Cras ultricies ligula sed magna dictum porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Nulla porttitor accumsan tincidunt. Nulla porttitor accumsan tincidunt. Sed porttitor lectus nibh. Donec sollicitudin molestie malesuada. Donec sollicitudin\n\nIn order to use our Service, you must meet a number of conditions, including but not limited to:\n\n- Enhance or improve User experience, our Site, or our Service.\n- Process transactions.\n- Send emails about our Site or respond to inquiries.\n- Send emails and updates about Conclude, including news and requests for agreement to amended legal documents such as this Privacy Policy and our - Terms of Service.\n- Perform any other function that we believ\n\n#### What are some advantages of using Figma\n\nfeugiat. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vivamus suscipit tortor eget felis porttitor volutpat. Cras ultricies ligula sed magna dictum porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Nulla porttitor accumsan tincidunt. Nulla porttitor accumsan tincidunt. Sed porttitor lectus nibh. Donec sollicitudin molestie malesuada. Donec sollicitudin";
						const data = {title:"Figma",meta_title:"",icon:"/images/integration/spotify.svg",description:"We collect certain identifying personal data when you Sign up to our Service such as your name,",draft:false};
						const _internal = {
							type: 'content',
							filePath: "/Users/zaidarivai/Desktop/website/omniheral_light/src/content/integrations/spotify.md",
							rawData: "\ntitle: \"Figma\"\ndescription: \"We collect certain identifying personal data when you Sign up to our Service such as your name,\"\nicon: /images/integration/spotify.svg\nmeta_title: \"\"\ndraft: false",
						};

export { _internal, body, collection, data, id, slug };
