const id = "testimonial.md";
						const collection = "sections";
						const slug = "testimonial";
						const body = "";
						const data = {enable:true,subtitle:"INSPIRING TESTIMONIALS",title:"Take an Look at Our Customers Stories",list:[{name:"Devon Lane",designation:"VP growth at Facebook",avatar:"/images/customers/1.jpg",company_logo:"/images/logo/1.png",title:"Efficient Experience with Superb Customer Support",content:"elementum sed sit amet. Nulla port titor accumsan tincidunt. Proin eget tortor risus. Vestibulum ac diam sit amet quam"},{name:"Guy Hawkins",designation:"VP growth at Facebook",avatar:"/images/customers/2.jpg",company_logo:"/images/logo/2.png",title:"Seamless Integration and Powerful Functionality",content:"elementum sed sit amet. Nulla port titor accumsan tincidunt. Proin eget tortor risus. Vestibulum ac diam sit amet quam"},{name:"Savannah Nguyen",designation:"VP growth at Facebook",avatar:"/images/customers/3.jpg",company_logo:"/images/logo/3.png",title:"Empowering Businesses with Cutting-Edge Solutions",content:"elementum sed sit amet. Nulla port titor accumsan tincidunt. Proin eget tortor risus. Vestibulum ac diam sit amet quam"},{name:"Ronald Richards",designation:"VP growth at Facebook",avatar:"/images/customers/4.jpg",company_logo:"/images/logo/1.png",title:"Revolutionizing Business with Scalable Solutions",content:"elementum sed sit amet. Nulla port titor accumsan tincidunt. Proin eget tortor risus. Vestibulum ac diam sit amet quam"}]};
						const _internal = {
							type: 'content',
							filePath: "/Users/zaidarivai/Desktop/website/omniheral_light/src/content/sections/testimonial.md",
							rawData: "\nenable: true\nsubtitle: \"INSPIRING TESTIMONIALS\"\ntitle: \"Take an Look at Our Customers Stories\"\n\n# Testimonials\nlist:\n  - name: \"Devon Lane\"\n    designation: \"VP growth at Facebook\"\n    avatar: \"/images/customers/1.jpg\"\n    company_logo: \"/images/logo/1.png\"\n    title: Efficient Experience with Superb Customer Support\n    content: \"elementum sed sit amet. Nulla port titor accumsan tincidunt. Proin eget tortor risus. Vestibulum ac diam sit amet quam\"\n  - name: \"Guy Hawkins\"\n    designation: \"VP growth at Facebook\"\n    avatar: \"/images/customers/2.jpg\"\n    company_logo: \"/images/logo/2.png\"\n    title: Seamless Integration and Powerful Functionality\n    content: \"elementum sed sit amet. Nulla port titor accumsan tincidunt. Proin eget tortor risus. Vestibulum ac diam sit amet quam\"\n  - name: \"Savannah Nguyen\"\n    designation: \"VP growth at Facebook\"\n    avatar: \"/images/customers/3.jpg\"\n    company_logo: \"/images/logo/3.png\"\n    title: Empowering Businesses with Cutting-Edge Solutions\n    content: \"elementum sed sit amet. Nulla port titor accumsan tincidunt. Proin eget tortor risus. Vestibulum ac diam sit amet quam\"\n  - name: \"Ronald Richards\"\n    designation: \"VP growth at Facebook\"\n    avatar: \"/images/customers/4.jpg\"\n    company_logo: \"/images/logo/1.png\"\n    title: Revolutionizing Business with Scalable Solutions\n    content: \"elementum sed sit amet. Nulla port titor accumsan tincidunt. Proin eget tortor risus. Vestibulum ac diam sit amet quam\"",
						};

export { _internal, body, collection, data, id, slug };
